import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";


const Settings: NextPage = () => {
  const { data, error, isLoading } = trpc.useQuery(["settings.update-auth"]);

  return (
    <>
      <Head>
        <title>Ustawienia</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        {data?.url && <a href={data.url}>Zaktualizuj ustawienia Gmaila</a>}
        {error && error.message}
      </main>
    </>
  );
};

export default Settings;
